config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # 管理者
  devise_for :admin, :controllers => {
    :registrations => 'admin/registrations',
    :sessions => 'admin/sessions'
  }

  # 管理者側
  namespace :admin do
    resources :end_users, only:[:show, :edit, :update, :index] do
      # フォロー、フォロワー
      get "relationships/follows" => "relationships#follows"
      get "relationships/fllowers" => "relationships#followers"
    end
    # 投稿記事
    resources :posts, only:[:index, :show, :edit, :update]
    # ジャンル
    resources :tags, only:[:index]
  end

  # エンドユーザー
  devise_for :end_users, :controllers => {
    :registrations => 'public/end_users/registrations',
    :sessions => 'public/end_users/sessions'
  }

  scope module: :public do
    get "/end_users/follower_ranking" => "end_users#follower_ranking"
    get "/end_users/post_ranking" => "end_users#post_ranking"
    resources :end_users, only: [:show, :edit, :update, :index] do
      # フォロー、フォロワー
      resource :relationships, only:[:create, :destroy]
      get "relationships/follows" => "relationships#following_end_users"
      get "relationships/followers" => "relationships#follower_end_users"
      # フォローする
      post 'follow' => 'relationships#follow', as: 'follow'
      # フォロー外す
      post 'unfollow' => 'relationships#unfollow', as: 'unfollow'
      get "/unsubscribe" => "end_users#unsubscribe"
      patch "/withdraw" => "end_users#withdraw"
      # 買い物
      resources :shoppings do
        # 食材
        resources :foods, only:[:create, :edit, :update, :destroy]
        delete "foods/destroy_all" => "foods#destroy_all"
      end
    end

    # 投稿記事いいね数ランキング
    get "/posts/favorited_ranking" => "posts#favorited_ranking"
     # 投稿記事コメント数ランキング
    get "/posts/commented_ranking" => "posts#commented_ranking"
    # 投稿記事
    resources :posts do
      # コメント
      resources :post_comments, only:[:create, :destroy]
      # いいね
      resource :favorites, only:[:create, :destroy]
    end
     # タグ絞り込み投稿の表示
    resources :tags do
      get 'posts' => 'posts#search'
    end
    # トップ
    root to: "homes#top"
    get "/about" => "homes#about"
    # タグ一覧
    get '/search' => 'search#search'
    # お問い合わせ関連
    post 'contacts/confirm' => 'contacts#confirm'
    post 'contacts/back' => 'contacts#back'
    get 'done' => 'contacts#done'
    resources :contacts, only:[:new, :create]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord

# お問い合わせ内容をプルダウン式で選択
  enum subject_name:{
    "利用方法に関して": 0, "利用規約に関して": 1, "その他のお問い合わせ": 2
  }
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # ランキング機能
  has_many :favorited_posts, through: :favorites, source: :post
  has_many :commented_posts, through: :post_comments, source: :post

  has_many :post_comments, dependent: :destroy
  has_many :shoppings, dependent: :destroy
  # foreign_key（FK）には、@user.xxxとした際に「@user.idがfollower_idなのかfollowed_idなのか」を指定します。
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # @user.booksのように、@user.yyyで、
  # そのユーザがフォローしている人orフォローされている人の一覧を出したい
  has_many :following_end_users, through: :followers, source: :followed
  # foreign_key（FK）には、@user.xxxとした際に「@user.idがfollower_idなのかfollowed_idなのか」を指定します。
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # @user.booksのように、@user.yyyで、
  # そのユーザがフォローしている人orフォローされている人の一覧を出したい
  has_many :follower_end_users, through: :followeds, source: :follower

  attachment :profile_image, destroy: false

  def following?(end_user)
    following_end_users.include?(end_user)
  end

  def follow(end_user_id)
    followers.create(followed_id: end_user_id)
  end

  def unfollow(end_user_id)
    followers.find_by(followed_id: end_user_id).destroy
  end

  def post_active_for_authentication?
    super && (is_deleted == false)
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :end_user
  belongs_to :post

end

app/models/food.rb
class Food < ApplicationRecord

  belongs_to :shopping

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :end_user
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :tag_maps, dependent: :destroy
  # tag_mapsテーブルを通してtagsテーブルを参照するように定義
  has_many :tags, through: :tag_maps

  # ランキング機能
  has_many :favorited_end_users, through: :favorites, source: :end_user
  has_many :commented_end_users, through: :post_comments, source: :end_user


  attachment :image

  enum three_meals:{
    "朝食":0, "昼食":1, "夕食":2
  }

  def favorited_by?(end_user)
    favorites.where(end_user_id: end_user.id).exists?
  end

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?   # @postに紐づいているタグが存在する場合、タグの名前を配列として全て取得
    old_tags = current_tags - sent_tags                           # 現在取得した@postに存在するタグから、送信されてきたタグを除いたタグをold_tagsとする
    new_tags = sent_tags - current_tags                           # 送信されたタグから、現在存在するタグを除いたタグをnew_tagsとする

    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)            # 古いタグを削除する
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)         # 新しいタグをデータベースに保存する
      self.tags << new_post_tag
    end
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :end_user
  belongs_to :post
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "EndUser"
  belongs_to :followed, class_name: "EndUser"
  
end

app/models/shopping.rb
class Shopping < ApplicationRecord

  belongs_to :end_user
  has_many :foods, dependent: :destroy

  attachment :image

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :tag_maps, dependent: :destroy, foreign_key: 'tag_id'
  # tag_mapsテーブルを通してpostテーブルを参照する
  has_many :posts, through: :tag_maps
  

end

app/models/tag_map.rb
class TagMap < ApplicationRecord

  #postとtagの中間テーブル
  belongs_to :post
  belongs_to :tag

  validates :post_id, presence: true
  validates :tag_id, presence: true

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to admin_post_path(@post)
  end

  private

  def post_params
    params.require(:post).permit(:is_deleted)
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper



end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/shoppings_helper.rb
module ShoppingsHelper
end

app/views/admin/posts/edit.html.erb
<main class = "main">
  <div class="main__blog">
    <h3 class = "main__blog--heading">
      投稿編集
    </h3>
    <div class="main__blog--edit">
      <table>
        <tr>
          <td><%= attachment_image_tag @post, :image, :fill, 100, 100, fallback: "no_image.jpg" %></td>
          <td><%= @post.title %></td>
          <td><%= @post.three_meals %></td>
          <td><%= @post.explain %></td>
          <td><%= @post.cooking_method %></td>
          <td>
            <% if @post.release_status == true %>
              <p>公開中</p>
            <% else %>
              <p>非公開</p>
            <% end %>
          </td>
        </tr>
      </table>
      <%= form_with model:@post,url: admin_post_path, local:true do |f| %>
        <div class="form-group">
          <%= f.radio_button :is_deleted, :false %>
          <%= f.label :is_deleted, "有効" %>
          <%= f.radio_button :is_deleted, :true %>
          <%= f.label :is_deleted, "無効" %>
        </div>
        <div class="form-group">
          <%= f.submit '更新', class: 'btn btn-secondary' %>
        </div>
      <% end %>
    </div>
  </div>
</main>

app/views/admin/posts/index.html.erb
<main class = "main">
  <div class="main__blog">
    <h3 class = "main__blog--heading">
      投稿一覧
    </h3>
    <div class="main__blog--index">
      <table>
        <% @posts.each do |post| %>
        <tr>
          <td>
            <%= link_to admin_post_path(post) do %>
              <%= attachment_image_tag post, :image, :fill, 100, 100, fallback: "no_image.jpg" %>
            <% end %>
          </td>
          <td><%= post.title %></td>
          <td><%= post.three_meals %></td>
          <td><%= post.explain %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</main>

app/views/admin/posts/show.html.erb
<main class = "main">
  <div class="main__blog">
    <h3 class = "main__blog--heading">
      投稿詳細
    </h3>
    <div class="main__blog--index">
      <table>
        <tr>
          <td><%= attachment_image_tag @post, :image, :fill, 100, 100, fallback: "no_image.jpg" %></td>
          <td><%= @post.title %><td>
          <td><%= @post.three_meals %></td>
          <td><%= @post.explain %></td>
          <td><%= @post.cooking_method %></td>
          <td>
            <% if @post.release_status == true %>
              <p>公開中</p>
            <% else %>
              <p>非公開</p>
            <% end %>
          </td>
          <td>
            <% if @post.is_deleted == false %>
              <p>有効</p>
            <% else %>
              <p>無効</p>
            <% end %>
          </td>
          <td><%= link_to '編集', edit_admin_post_path(@post) %></td>
        </tr>
      </table>
    </div>
  </div>
</main>