config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # 管理者
  devise_for :admin, :controllers => {
    :registrations => 'admin/registrations',
    :sessions => 'admin/sessions'
  }

  # 管理者側
  namespace :admin do
    resources :end_users, only:[:show, :edit, :update, :index] do
      # フォロー、フォロワー
      get "relationships/follows" => "relationships#follows"
      get "relationships/fllowers" => "relationships#followers"
    end
    # 投稿記事
    resources :posts, only:[:index, :show, :edit, :update]
    # ジャンル
    resources :tags, only:[:index]
  end

  # エンドユーザー
  devise_for :end_users, :controllers => {
    :registrations => 'public/end_users/registrations',
    :sessions => 'public/end_users/sessions'
  }

  scope module: :public do
    get "/end_users/follower_ranking" => "end_users#follower_ranking"
    get "/end_users/post_ranking" => "end_users#post_ranking"
    resources :end_users, only: [:show, :edit, :update, :index] do
      # フォロー、フォロワー
      resource :relationships, only:[:create, :destroy]
      get "relationships/follows" => "relationships#following_end_users"
      get "relationships/followers" => "relationships#follower_end_users"
      # フォローする
      post 'follow' => 'relationships#follow', as: 'follow'
      # フォロー外す
      post 'unfollow' => 'relationships#unfollow', as: 'unfollow'
      get "/unsubscribe" => "end_users#unsubscribe"
      patch "/withdraw" => "end_users#withdraw"
      # 買い物
      resources :shoppings do
        # 食材
        resources :foods, only:[:create, :edit, :update, :destroy]
        delete "foods/destroy_all" => "foods#destroy_all"
      end
    end

    # 投稿記事いいね数ランキング
    get "/posts/favorited_ranking" => "posts#favorited_ranking"
     # 投稿記事コメント数ランキング
    get "/posts/commented_ranking" => "posts#commented_ranking"
    # 投稿記事
    resources :posts do
      # コメント
      resources :post_comments, only:[:create, :destroy]
      # いいね
      resource :favorites, only:[:create, :destroy]
    end
     # タグ絞り込み投稿の表示
    resources :tags do
      get 'posts' => 'posts#search'
    end
    # トップ
    root to: "homes#top"
    get "/about" => "homes#about"
    # タグ一覧
    get '/search' => 'search#search'
    # お問い合わせ関連
    post 'contacts/confirm' => 'contacts#confirm'
    post 'contacts/back' => 'contacts#back'
    get 'done' => 'contacts#done'
    resources :contacts, only:[:new, :create]
  end
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # ランキング機能
  has_many :favorited_posts, through: :favorites, source: :post
  has_many :commented_posts, through: :post_comments, source: :post

  has_many :post_comments, dependent: :destroy
  has_many :shoppings, dependent: :destroy
  # foreign_key（FK）には、@user.xxxとした際に「@user.idがfollower_idなのかfollowed_idなのか」を指定します。
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # @user.booksのように、@user.yyyで、
  # そのユーザがフォローしている人orフォローされている人の一覧を出したい
  has_many :following_end_users, through: :followers, source: :followed
  # foreign_key（FK）には、@user.xxxとした際に「@user.idがfollower_idなのかfollowed_idなのか」を指定します。
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # @user.booksのように、@user.yyyで、
  # そのユーザがフォローしている人orフォローされている人の一覧を出したい
  has_many :follower_end_users, through: :followeds, source: :follower

  attachment :profile_image, destroy: false

  def following?(end_user)
    following_end_users.include?(end_user)
  end

  def follow(end_user_id)
    followers.create(followed_id: end_user_id)
  end

  def unfollow(end_user_id)
    followers.find_by(followed_id: end_user_id).destroy
  end

  def post_active_for_authentication?
    super && (is_deleted == false)
  end

end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController

  def index
    @end_users = EndUser.all
  end

  def show
    @end_user = EndUser.find(params[:id])
  end

  def edit
    @end_user = EndUser.find(params[:id])
  end

  def update
    @end_user = EndUser.find(params[:id])
    @end_user.update(end_user_params)
    redirect_to admin_end_user_path(@end_user)
  end


  private

  def end_user_params
    params.require(:end_user).permit(:is_deleted)
  end

end

app/controllers/end_users/confirmations_controller.rb
# frozen_string_literal: true

class EndUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/end_users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class EndUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/end_users/passwords_controller.rb
# frozen_string_literal: true

class EndUsers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/end_users/registrations_controller.rb
# frozen_string_literal: true

class EndUsers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/end_users/sessions_controller.rb
# frozen_string_literal: true

class EndUsers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/end_users/unlocks_controller.rb
# frozen_string_literal: true

class EndUsers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper



end

app/views/admin/end_users/edit.html.erb
<main class = "main">
  <div class="main__blog">
    <h3 class = "main__blog--heading">
      ユーザー編集
    </h3>
    <div class="main__blog--edit">
      <table>
        <tr>
          <td><%= attachment_image_tag @end_user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></td>
          <td><%= @end_user.last_name + @end_user.first_name %></td>
          <td><%= @end_user.introduction %></td>
        </tr>
      </table>
      <%= form_with model:@end_user,url: admin_end_user_path, local:true do |f| %>
        <div class="form-group">
          <%= f.radio_button :is_deleted, :false %>
          <%= f.label :is_deleted, "有効" %>
          <%= f.radio_button :is_deleted, :true %>
          <%= f.label :is_deleted, "退会" %>
        </div>
        <div class="form-group">
          <%= f.submit '更新', class: 'btn btn-secondary' %>
        </div>
      <% end %>
    </div>
  </div>
</main>

app/views/admin/end_users/index.html.erb
<main class = "main">
  <div class="main__blog">
    <h3 class = "main__blog--heading">
        ユーザー一覧
    </h3>
    <div class="main__blog--index">
      <table>
        <tr>
          <th></th>
          <th>名前</th>
          <th></th>
          <th></th>
        </tr>
        <% @end_users.each do |end_user| %>
        <tr>
          <td>
            <%= link_to admin_end_user_path(end_user) do %>
            <%= attachment_image_tag end_user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
            <% end %>
          </td>
          <td><%= end_user.last_name + end_user.first_name %></td>
          <td><%= end_user.introduction %></td>
          <td>
            <% if end_user.is_deleted == false %>
              <p class ="available">有効</p>
            <% else %>
              <p class ="invalid">退会</p>
            <% end %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</main>

app/views/admin/end_users/show.html.erb
<main class = "main">
  <div class="main__blog">
    <h3 class = "main__blog--heading">
      ユーザー詳細
    </h3>
    <div class="main__blog--user-info">
      <table>
        <tr>
          <td><%= attachment_image_tag @end_user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></td>
          <td><%= @end_user.last_name + @end_user.first_name %></td>
          <td><%= @end_user.introduction %></td>
          <td>
            <% if @end_user.is_deleted == false %>
              <p class ="available">有効</p>
            <% else %>
              <p class ="invalid">退会</p>
            <% end %>
          </td>
          <td><%= link_to '編集', edit_admin_end_user_path(@end_user) %></td>
        </tr>
      </table>
    </div>
  </div>
</main>